/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import java.util.StringTokenizer; 
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import model.conexiondb;

/**
 *
 * @author alonso
 */
public class agregarAlumno extends javax.swing.JInternalFrame {

    
      int  []idcurso = null;
    /**
     * Creates new form agregarAlumno
     */
    public agregarAlumno() {
        initComponents();
        
         try {
            try
{
Class.forName("com.mysql.jdbc.Driver");
} catch (Exception e)
{
e.printStackTrace();
}
     Connection conexion = DriverManager.getConnection (
             "jdbc:mysql://"+conexiondb.getDbserver()+"/"+conexiondb.getDbname(),conexiondb.getDbuser(), conexiondb.getDbpass());
          Statement s = conexion.createStatement(); 
             ResultSet rs = s.executeQuery ("SELECT * FROM `Curso`");
          
           
          DefaultListModel modelo = new DefaultListModel();
     
          int e=0;
          while(rs.next()){
              modelo.addElement(rs.getString("nombre")+"-"+rs.getInt("idCurso"));
              
          }
           
          lCursos.setModel(modelo);
         
          
             
            
            
        s.close();
        conexion.close();
        } catch (SQLException ex) {
            Logger.getLogger(agregarCurso.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tnombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lCursos = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("Agregar Estudiante");

        jLabel1.setText("Nombre:");

        jLabel2.setText("Cursos:");

        jScrollPane1.setViewportView(lCursos);

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Salir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(14, 14, 14)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(tnombre)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Object cursos[]= lCursos.getSelectedValues();
   
        
         String nombre;
        nombre= tnombre.getText();
       String idalumno = null;
      boolean exito= false;
        
           try {
            try
{
Class.forName("com.mysql.jdbc.Driver");
} catch (Exception e)
{
e.printStackTrace();
}
     Connection conexion = DriverManager.getConnection (
             "jdbc:mysql://"+conexiondb.getDbserver()+"/"+conexiondb.getDbname(),conexiondb.getDbuser(), conexiondb.getDbpass());
          Statement s = conexion.createStatement(); 
            int executeUpdate = s.executeUpdate ("INSERT INTO Alumno (nombre) VALUES ('"+nombre+"')");
       if(executeUpdate==1){
             ResultSet rs = s.executeQuery ("SELECT * FROM `Alumno` ORDER BY `idAlumno`  ASC");
             while(rs.next()){
                 idalumno=rs.getString("idAlumno");
             }
           
                javax.swing.JOptionPane.showMessageDialog(null, "Se ingreso correctamente el Alumno: "+nombre+"\n con el codigo: "+idalumno);
                exito=true;
              
            }else if(executeUpdate==0){
                javax.swing.JOptionPane.showMessageDialog(null, "no se logro ingresar");
            }
           
        s.close();
        conexion.close();
        } catch (SQLException ex) {
            Logger.getLogger(agregarCurso.class.getName()).log(Level.SEVERE, null, ex);
   
            
            
        }
           // iteraciones
           
           
           
           if(exito){
           for(int i=0;i<cursos.length;i++){
               
               StringTokenizer st = new StringTokenizer(cursos[i].toString(),"-"); 
               String nombrecur=st.nextToken();
               String Cursid=st.nextToken();
               
              // System.out.println(Cursid+" "+idalumno+" "+i);
              
           try {
            try
{
Class.forName("com.mysql.jdbc.Driver");
} catch (Exception e)
{
e.printStackTrace();
}
     Connection conexion = DriverManager.getConnection (
             "jdbc:mysql://"+conexiondb.getDbserver()+"/"+conexiondb.getDbname(),conexiondb.getDbuser(), conexiondb.getDbpass());
          Statement s = conexion.createStatement(); 
            int executeUpdate = s.executeUpdate ("INSERT INTO nota (parcial, final, Alumno_idAlumno, Curso_idCurso) VALUES ('0', '0', '"+idalumno+"', '"+Cursid+"')");
      
           
        s.close();
        conexion.close();
        } catch (SQLException ex) {
            Logger.getLogger(agregarCurso.class.getName()).log(Level.SEVERE, null, ex);
   
            
            
        }  
           }
           
           lCursos.clearSelection();
            
           tnombre.setText(null);
      this.setVisible(false);
           }
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lCursos;
    private javax.swing.JTextField tnombre;
    // End of variables declaration//GEN-END:variables
}
