/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import model.conexiondb;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ricardo
 */
public class agregarCurso extends javax.swing.JInternalFrame {

    /**
     * Creates new form agregarCurso
     */
    public agregarCurso() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tnombrec = new javax.swing.JTextField();
        bagregarc = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("Agregar Curso");

        jLabel1.setText("Nombre:");

        bagregarc.setText("Agregar");
        bagregarc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bagregarcActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tnombrec, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bagregarc)
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tnombrec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bagregarc))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bagregarcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bagregarcActionPerformed
        // TODO add your handling code here:
        String nombre;
        nombre= tnombrec.getText();
        
        
           try {
            try
{
Class.forName("com.mysql.jdbc.Driver");
} catch (Exception e)
{
e.printStackTrace();
}
     Connection conexion = DriverManager.getConnection (
             "jdbc:mysql://"+conexiondb.getDbserver()+"/"+conexiondb.getDbname(),conexiondb.getDbuser(), conexiondb.getDbpass());
          Statement s = conexion.createStatement(); 
            int executeUpdate = s.executeUpdate ("INSERT INTO Curso (nombre) VALUES ('"+nombre+"')");
       
            if(executeUpdate==1){
                javax.swing.JOptionPane.showMessageDialog(null, "Se ingreso correctamente el curso: "+nombre);
                
              
            }else if(executeUpdate==0){
                javax.swing.JOptionPane.showMessageDialog(null, "no se logro ingresar");
            }
        s.close();
        conexion.close();
        } catch (SQLException ex) {
            Logger.getLogger(agregarCurso.class.getName()).log(Level.SEVERE, null, ex);
        }
           tnombrec.setText(null);
      this.setVisible(false);
      
    }//GEN-LAST:event_bagregarcActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bagregarc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField tnombrec;
    // End of variables declaration//GEN-END:variables
}
