/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.conexiondb;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ricardo
 */
public class modificarCurso extends javax.swing.JInternalFrame {
    int selec=-1;
    /**
     * Creates new form modificarCurso
     */
    public modificarCurso() {
        initComponents();
                try {
            try
{
Class.forName("com.mysql.jdbc.Driver");
} catch (Exception e)
{
e.printStackTrace();
}
     Connection conexion = DriverManager.getConnection (
             "jdbc:mysql://"+conexiondb.getDbserver()+"/"+conexiondb.getDbname(),conexiondb.getDbuser(), conexiondb.getDbpass());
          Statement s = conexion.createStatement(); 
             ResultSet rs = s.executeQuery ("SELECT * FROM `Curso`");
           DefaultTableModel modelo= new DefaultTableModel();
           tablaCursos.setModel(modelo);
           modelo.addColumn("id");
           modelo.addColumn("Curso");
           
             while(rs.next()){
               Object []filas =new Object[2];
               filas[0]=rs.getInt("idCurso");
               filas[1]=rs.getString("nombre");
               modelo.addRow(filas);
             }
             
             
            
            
            
        s.close();
        conexion.close();
        } catch (SQLException ex) {
            Logger.getLogger(agregarCurso.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCursos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("Lista, Modificar Cursos");

        tablaCursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Curso"
            }
        ));
        tablaCursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaCursosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaCursos);

        jButton1.setText("Modificar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Borrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Actualizar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(17, 17, 17)
                .addComponent(jButton2)
                .addContainerGap(213, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaCursosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaCursosMouseClicked
        // TODO add your handling code here:
        selec=tablaCursos.rowAtPoint(evt.getPoint());
    }//GEN-LAST:event_tablaCursosMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String id= tablaCursos.getValueAt(selec, 0).toString();
        System.out.println(id);
        System.out.println(tablaCursos.getValueAt(selec, 1).toString());
          try {
            try
{
Class.forName("com.mysql.jdbc.Driver");
} catch (Exception e)
{
e.printStackTrace();
}
     Connection conexion = DriverManager.getConnection (
             "jdbc:mysql://"+conexiondb.getDbserver()+"/"+conexiondb.getDbname(),conexiondb.getDbuser(), conexiondb.getDbpass());
          Statement s = conexion.createStatement(); 
         
          
            int executeUpdate = s.executeUpdate ("UPDATE Curso SET nombre='"+tablaCursos.getValueAt(selec, 1).toString()+"' WHERE idCurso="+id);
       
            if(executeUpdate==1){
                javax.swing.JOptionPane.showMessageDialog(null, "Se Actualizo la informacion");
            }else if(executeUpdate==0){
                javax.swing.JOptionPane.showMessageDialog(null, "Error!! no se puedo ingresar la información");
            }
        s.close();
        conexion.close();
        } catch (SQLException ex) {
            Logger.getLogger(modificarCurso.class.getName()).log(Level.SEVERE, null, ex);
        }
             
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
               try {
            try
{
Class.forName("com.mysql.jdbc.Driver");
} catch (Exception e)
{
e.printStackTrace();
}
     Connection conexion = DriverManager.getConnection (
             "jdbc:mysql://"+conexiondb.getDbserver()+"/"+conexiondb.getDbname(),conexiondb.getDbuser(), conexiondb.getDbpass());
          Statement s = conexion.createStatement(); 
             ResultSet rs = s.executeQuery ("SELECT * FROM `Curso`");
           DefaultTableModel modelo= new DefaultTableModel();
           tablaCursos.setModel(modelo);
           modelo.addColumn("id");
           modelo.addColumn("Curso");
           
             while(rs.next()){
               Object []filas =new Object[2];
               filas[0]=rs.getInt("idCurso");
               filas[1]=rs.getString("nombre");
               modelo.addRow(filas);
             }
             
             
            
            
            
        s.close();
        conexion.close();
        } catch (SQLException ex) {
            Logger.getLogger(agregarCurso.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String id=tablaCursos.getValueAt(selec, 0).toString();
               try {
            try
{
Class.forName("com.mysql.jdbc.Driver");
} catch (Exception e)
{
e.printStackTrace();
}
     Connection conexion = DriverManager.getConnection (
             "jdbc:mysql://"+conexiondb.getDbserver()+"/"+conexiondb.getDbname(),conexiondb.getDbuser(), conexiondb.getDbpass());
          Statement s = conexion.createStatement(); 
         int executeUpdate = s.executeUpdate ("DELETE from Curso WHERE idCurso="+id);
       
            if(executeUpdate==1){
                javax.swing.JOptionPane.showMessageDialog(null, "Borro el curso");
                     jButton3ActionPerformed(evt);                                   

            }else if(executeUpdate==0){
                javax.swing.JOptionPane.showMessageDialog(null, "Error!! no se pudo borrar");
            }
             
             
            
            
            
        s.close();
        conexion.close();
        } catch (SQLException ex) {
            Logger.getLogger(agregarCurso.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaCursos;
    // End of variables declaration//GEN-END:variables
}
